# Generated by Django 5.0.4 on 2024-04-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_patientprofile_user_doctor_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=100)),
                ('date_of_diag', models.DateField()),
                ('treatments', models.CharField(max_length=200)),
                ('add_info', models.TextField()),
                ('report', models.FileField(blank=True, upload_to='doc')),
            ],
        ),
    ]
