# Generated by Django 5.0.4 on 2024-05-02 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_medicaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldata',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.patient'),
            preserve_default=False,
        ),
    ]
