# Generated by Django 5.0 on 2024-05-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='patient_username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
